name: Compile Newton Firmware
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup PlatformIO
        run: pip install -U platformio
      - name: Build Firmware
        run: pio run -d src/  # If this fails, change this line to: run: pio run
      - name: Upload Binary
        uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: src/.pio/build/esp32s3/firmware.bin
          
